# Generated by Django 5.2 on 2025-05-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('In Progress', 'В работе'), ('Done', 'Завершено')], default='new', max_length=20, verbose_name='Status'),
        ),
    ]
