# Generated by Django 5.2 on 2025-05-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('', '---------'), ('new', 'New'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='new', max_length=20, verbose_name='Status'),
        ),
    ]
