name: my-check

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.8]
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_SETTINGS_MODULE: task_manager.settings
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv and dependencies
        run: |
          pip install uv
          uv pip install -e .[dev]
          uv pip install --system . coverage

      - name: Run migrations
        run: make migrate

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test

      - name: Upload coverage to QLTY
        uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: reports/lcov.info
          skip-errors: false
        
      - name: Debug token
        run: |
          echo "QLTY_TOKEN exists: ${{ secrets.QLTY_COVERAGE_TOKEN != '' }}"
        
      - name: Debug lcov file
        run: |
          file reports/lcov.info
          wc -l reports/lcov.info