name: my-check

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.8]
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_SETTINGS_MODULE: task_manager.settings
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv and dependencies
        run: |
          pip install uv
          make install  # uv sync

      - name: Run migrations
        run: make migrate

      - name: Run linter
        run: make lint

      - name: Run tests and upload coverage
        env:
          QLTY_TOKEN: ${{ secrets.QLTY_TOKEN }}
        run: |
          make test
          curl -Os https://qlty.sh/upload
          chmod +x upload
          ./upload --token $QLTY_TOKEN --format coverage.py
